[project]
name = 'Tokenized-Retail-Experience-Personalization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumer-identity]
path = 'contracts/consumer-identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.engagement-tracking]
path = 'contracts/engagement-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.preference-tracking]
path = 'contracts/preference-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.recommendation]
path = 'contracts/recommendation.clar'
clarity_version = 2
epoch = 2.5

[contracts.retailer-verification]
path = 'contracts/retailer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
